const demoUsers = [
  {
    firstName: "Usuario",
    lastName: "Demo",
    email: "test@test1.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 2",
    lastName: "Demo",
    email: "test@test2.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 3",
    lastName: "Demo",
    email: "test@test3.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 4",
    lastName: "Demo",
    email: "test@test4.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 5",
    lastName: "Demo",
    email: "test@test5.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 6",
    lastName: "Demo",
    email: "test@test6.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 7",
    lastName: "Demo",
    email: "test@test7.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 8",
    lastName: "Demo",
    email: "test@test8.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 9",
    lastName: "Demo",
    email: "test@test9.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 10",
    lastName: "Demo",
    email: "test@test10.com",
    password: "Alkemy@123456*",
    roleId: 1,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 11",
    lastName: "Demo",
    email: "test@test11.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 12",
    lastName: "Demo",
    email: "test@test12.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 13",
    lastName: "Demo",
    email: "test@test13.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 14",
    lastName: "Demo",
    email: "test@test14.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 15",
    lastName: "Demo",
    email: "test@test15.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 16",
    lastName: "Demo",
    email: "test@test16.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 17",
    lastName: "Demo",
    email: "test@test17.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 18",
    lastName: "Demo",
    email: "test@test18.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 19",
    lastName: "Demo",
    email: "test@test19.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: "Usuario 20",
    lastName: "Demo",
    email: "test@test20.com",
    password: "Alkemy@123456*",
    roleId: 2,
    photo:"https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = demoUsers;
